GET http://localhost:9000/ HTTP/1.1

###

GET http://localhost:9000/ HTTP/1.1

###

POST http://localhost:9000/slackBotAPI HTTP/1.1
content-type: application/json

{
    "challenge": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST https://research-assistant-organizer.web.app/api/slackbot HTTP/1.1
content-type: application/json

{
    "challenge": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST https://studio.twilio.com/v2/Flows/FW116a33462af517b60245399b3e05f3c8/Executions HTTP/1.1
content-type: application/json

{
    "first": "second"
}